version: '3'

services:
  db:
    restart: always
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tmcit
      MYSQL_DATABASE: Taad_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db/data:/var/lib/mysql
    - ./log/mysql:/var/log/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./initdb.d/:/docker-entrypoint-initdb.d
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci   
    ports:
      - 3306:3306
  
    networks:
      python_network:
        ipv4_address: 192.168.2.2              


  python3:
    restart: always
    build:
      context: ./
      dockerfile: ./python/Dockerfile      
    container_name: "python3"
    working_dir: "/root/src"
    ports:
      - 8080:80
    tty: true
    volumes:
      - ./python:/root/src
    links:
      - db 
    networks:
      - python_network

networks: 
  python_network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 192.168.2.0/24
